list = [
    # Web
    [".html", "text/html"],
    [".css", "text/css"],
    [".js", "text/javascript"],
    [".json", "application/json"],
    [".ico", "image/x-icon"],
    [".otf", "font/otf"],
    [".ttf", "font/ttf"],
    [".woff", "font/woff"],
    [".woff2", "font/woff2"],
    # Image
    [".jpg", "image/jpeg"],
    [".jpeg", "image/jpeg"],
    [".png", "image/png"],
    [".gif", "image/gif"],
    [".avif", "image/avif"],
    [".webp", "image/webp"],
    [".svg", "image/svg+xml"],
    [".apng", "image/apng"],
    # Audio
    [".aac", "audio/aac"],
    [".mp3", "audio/mpeg"],
    [".ogg", "audio/ogg"],
    [".wav", "audio/wav"],
    # Video
    [".mp4", "video/mp4"],
    [".mpeg", "video/mpeg"],
    [".webm", "video/webm"],
    [".ts", "video/mp2t"],
    [".avi", "video/x-msvideo"],
    # Other
    [".txt", "text/plain"],
    [".pdf", "application/pdf"],
]